n = int(input("dimmi un numero"))
print("Ecco il doppio", n*2)
print("Ecco il triplo", n*3)
print("Ecco il quadruplo", n*4)
print("Ecco il quintuplo", n*5)
n = int(input("Dimmi il tuo nome")
m = int(input("Dimmi il tuo cognome")
v = int(input("dimmi la tua età")
c = int(input("dimmi il tuo compleanno")
print("Ecco i tuoi dati:", n, m, v, c,)
